name: silent_speech
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - numpy=1.26.4
  - pip=24.2
  - python=3.10.14
  - requests=2.32.3
  - setuptools=71.0.4
  - tbb=2021.12.0
  - tk=8.6.13
  - typing_extensions=4.12.2
  - urllib3=2.2.2
  - wheel=0.43.0
  - pip:
      - absl-py==2.1.0
      - aiocache==0.12.2
      - aiohappyeyeballs==2.3.4
      - aiohttp==3.10.0
      - aiosignal==1.3.1
      - altair==5.3.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.4.0
      - arrow==1.3.0
      - asciitree==0.3.3
      - asttokens==2.4.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - audioread==3.0.1
      - av==12.3.0
      - bark==0.1.5
      - beautifulsoup4==4.12.3
      - blosc2==2.7.1
      - boto3==1.34.152
      - botocore==1.34.152
      - bounded-pool-executor==0.0.3
      - brainflow==5.13.0
      - bravado==11.0.3
      - bravado-core==6.1.1
      - cffi==1.16.0
      - click==8.1.7
      - cmake==3.30.2
      - colorama==0.4.6
      - comm==0.2.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - datasets==2.20.0
      - debugpy==1.8.2
      - decorator==5.1.1
      - dill==0.3.8
      - distance==0.1.3
      - distro==1.9.0
      - einops==0.8.0
      - einx==0.3.0
      - elephant==1.1.0
      - encodec==0.1.1
      - evaluate==0.4.2
      - exceptiongroup==1.2.2
      - executing==2.0.1
      - fasteners==0.19
      - fire==0.6.0
      - flashlight-text==0.0.7
      - fonttools==4.53.1
      - fqdn==1.5.1
      - frozendict==2.4.4
      - frozenlist==1.4.1
      - fsspec==2024.5.0
      - funcy==2.0
      - future==1.0.0
      - g2p-en==2.1.0
      - git-filter-repo==2.45.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - h11==0.14.0
      - h5py==3.11.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.24.5
      - hydra-core==1.3.2
      - hyperpyyaml==1.2.2
      - imageio==2.34.2
      - importlib-resources==6.4.0
      - inflect==7.3.1
      - iniconfig==2.0.0
      - ipykernel==6.29.5
      - ipython==8.26.0
      - isoduration==20.11.0
      - jedi==0.19.1
      - jiwer==3.0.4
      - jmespath==1.0.1
      - joblib==1.4.2
      - jsonpointer==3.0.0
      - jsonref==1.1.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.2
      - jupyter-core==5.7.2
      - kenlm==0.2.0
      - keopscore==2.2.3
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - librosa==0.10.2.post1
      - lightning-utilities==0.11.6
      - llvmlite==0.43.0
      - markdown-it-py==3.0.0
      - matplotlib==3.9.1
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - monotonic==1.6
      - more-itertools==10.3.0
      - msgpack==1.0.8
      - multidict==6.0.5
      - multiprocess==0.70.16
      - ndindex==1.8
      - neo==0.13.2
      - neptune-client==0.16.18
      - nest-asyncio==1.6.0
      - nltk==3.8.1
      - numba==0.60.0
      - numcodecs==0.13.0
      - numexpr==2.10.1
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - openai==1.37.2
      - openai-whisper==20231117
      - opt-einsum==3.3.0
      - packaging==24.1
      - pandas==2.2.2
      - parso==0.8.4
      - platformdirs==4.2.2
      - pluggy==1.5.0
      - pooch==1.8.2
      - pqdm==0.2.0
      - praat-textgrids==1.4.0
      - prompt-toolkit==3.0.47
      - psutil==6.0.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyarrow==17.0.0
      - pyarrow-hotfix==0.6
      - pybind11==2.13.1
      - pycparser==2.22
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pyglet==2.0.16
      - pygments==2.18.0
      - pyjwt==2.9.0
      - pykeops==2.2.3
      - pyparsing==3.1.2
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.15.0
      - pyret==0.6.0
      - pytest==8.3.2
      - python-dateutil==2.9.0.post0
      - python-speech-features==0.6
      - pytorch-lightning==2.3.3
      - pytorch-warmup==0.1.1
      - pytz==2024.1
      - pywin32==306
      - pyzmq==26.0.3
      - quantities==0.15.0
      - rapidfuzz==3.9.5
      - referencing==0.35.1
      - regex==2024.7.24
      - requests-oauthlib==2.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.1
      - rpds-py==0.19.1
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.8
      - s3transfer==0.10.2
      - safetensors==0.4.3
      - scikit-image==0.24.0
      - scikit-learn==1.5.1
      - scipy==1.14.0
      - seaborn==0.13.2
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - simplejson==3.19.2
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - sounddevice==0.4.7
      - soundfile==0.12.1
      - soupsieve==2.5
      - soxr==0.4.0
      - speechbrain==1.0.0
      - stack-data==0.6.3
      - swagger-spec-validator==3.0.4
      - sympy==1.13.1
      - tables==3.9.2
      - tenacity==9.0.0
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - tifffile==2024.7.24
      - tiktoken==0.7.0
      - tokenizers==0.19.1
      - toolz==0.12.1
      - torch==2.4.0
      - torchaudio==2.4.0
      - torchmetrics==1.4.0.post0
      - torchtext==0.18.0
      - torchvision==0.19.0
      - tornado==6.4.1
      - tqdm==4.66.4
      - traitlets==5.14.3
      - transformers==4.43.3
      - typeguard==4.3.0
      - typer==0.12.3
      - types-python-dateutil==2.9.0.20240316
      - tzdata==2024.1
      - unidecode==1.3.8
      - uri-template==1.3.0
      - vector-quantize-pytorch==1.15.6
      - wcwidth==0.2.13
      - webcolors==24.6.0
      - websocket-client==1.8.0
      - websockets==12.0
      - xxhash==3.4.1
      - yarl==1.9.4
      - zarr==2.18.2
